### ISSUE TITLE
The .py file referenced from Addon.xml should be as minimal as possible 

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/generator-kodi-addon#11]
To get best speed the default python file should be bare minimal and then call the main file from that. Reason is the main referenced one isn't kept compiled while the others are kept compiled

**Comment by razzeee** [comment]
So should we do a minimal startup/main.py in the main folder and then just call an entry point in the resource/lib folder?
Does this make sense for all addon types? Even contextmenus?

**Comment by MartijnKaijser** [comment]
any file that could become quite big. Not sure where we should put the threshold

**Comment by razzeee** [comment]
Let's just default to that, for every type that can set a *.py file to be called via addon.xml
