### ISSUE TITLE
Use same python code style in every template 

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/generator-kodi-addon#12]
Currently there's still differences between the templates and they should be matched up as much as possible

**Comment by razzeee** [comment]
Yes, I will enforce PEP8 on all, with a follow up PR to https://github.com/xbmc/generator-kodi-addon/pull/6 as soon as that's merged

**Comment by razzeee** [comment]
Please check https://github.com/xbmc/generator-kodi-addon/commit/3e7248e201162cb3763f5e1986db23f8d42a0bb8 if I missed something
