### ISSUE TITLE
Boilerplate for common code

### ISSUE THREAD

**Issue by razzeee** [xbmc/generator-kodi-addon#3]
We should embed some common code like translation handling. 

Any more ideas what might be nice to have?

**Comment by phate89** [comment]
Some example code to handle the url parsing and adding a listitem it's something we should add (or directly using tamland's addon).
In services we should add an example main loop with waitforabort
For specific addons we can go further. For example I was thinking to subtitle or contextmenu addons we can show how to grab info needed to get the subtitle (title, year season, episode, ids etc etc)

**Comment by enen92** [comment]
@Razzeee do you think it is viable to automatically generate a script.module out of a pipy package?

**Comment by razzeee** [comment]
Very interesting idea, we'll have to look if there is a subgenerator somewhere that can do that. Or maybe grab releases from github pages.

**Comment by razzeee** [comment]
@enen92 might be possible using some npm packages like https://github.com/lukaszb/pypi to talk with pypi let the user choose what he wants and then download the version. The other stuff should be doable via the file management classes of js.

**Comment by enen92** [comment]
Great! My question was more if you think that option would fall into the purpose of this tool and lesser on how that would be achieved though :)

**Comment by razzeee** [comment]
Well I don't think updating modules is very hard, but automating it would be wonderful (less errors)
Unfortunatly this generator is only really fit for creating something and improving upon it.

While it could work, to just generate a new module and replace it in your local checkout of the repo and then push it, it seems kind of "backwards"?
Maybe just have a convention/config file in our modules and parse that with a weapon of our choice. Grab the new pypi files and replace the old ones. Thus keeping the action in your git tree make stuff easier?

**Comment by razzeee** [comment]
@phate89 
> Some example code to handle the url parsing and adding a listitem it's something we should add (or directly using tamland's addon).

Boilerplate now uses tamlands addon

> In services we should add an example main loop with waitforabort

Done

> For specific addons we can go further. For example I was thinking to subtitle or contextmenu addons we can show how to grab info needed to get the subtitle (title, year season, episode, ids etc etc)

Subtitle addon type is not yet supported. If you have some expertise on those, a little help or even a PR would be cool. Not sure what you would want to do for contextmenus

**Comment by phate89** [comment]
Not sure if it's useful now but for the future might be useful to have different versions of the file according to the target version. So if we add something to improve kodi python api the addon uses already all the latest stuff..

**Comment by razzeee** [comment]
Yes, absolutely. I'm not sure how we would organize the folders. Been thinking of having also c++ generators added, but from the looks I had at those addons so far, they seem pretty hard to automate/different. (Read as in not worth it probably)

**Comment by phate89** [comment]
binary addons? Until we don't have a binary repo it's probably not worh it..

**Comment by razzeee** [comment]
Merged https://github.com/xbmc/generator-kodi-addon/pull/6 should be enough for now
