### ISSUE TITLE
Error 1st Run Newbee

### ISSUE THREAD

**Issue by Higgybees** [xbmc/generator-kodi-addon#43]
Hi on first run folder created then the following. I am running as admin Win 10
*** Please tell me who you are. 
Run
git config - - user. email "you@example.com"
git config - - user. name "Your Name"
to set your account's default identity. 
omitt - - global to set the identity only in this reposiry.
fatal: unable to auto-detect email address (got 'Frederick@freds_pc.(none)')
Can you help please want to open a Web page on Kodi android. 
Thanks 
Fred
Ps where are files saved

**Comment by razzeee** [comment]
To resolve your problem you need to setup your local git, as explained in the error by the `git config` commands. Make sure you have git installed.

I have no idea if it's possible to open a webpage in a browser from kodi. I would be surprised.

**Comment by Higgybees** [comment]
Thanks for the reply. As I say I'm a new bee. Saves me pursuing a lost
cause.
Fred
