### ISSUE TITLE
Convention for "kodi" classes

### ISSUE THREAD

**Issue by razzeee** [xbmc/generator-kodi-addon#8]
Just something to discuss:

What I'm doing with trakt is, splitting methods between two files, for e.g.:
- `kodiUtilities.py` is everything I would have in a utilities class, that binds to one of the xbmc/kodi imports
- `utilities.py` gets every method that doesn't have a dependency to one of these

So now I can write unit tests for `utilities.py`, pretty easily.
Here the question, is this a good practice? Is this a practice we want to push?

@phil65 @MartijnKaijser @enen92 @BigNoid @phate89

**Comment by phate89** [comment]
In my personal module I splitted utilities in 3 modules:
Kodi utilities
Utilities
Web utilities 
I also try to separate the Kodi code from generic code in separate functions for every addon
So it seems a good approach to me

**Comment by razzeee** [comment]
Would like some more feedback here

**Comment by enen92** [comment]
I agree with your approach, keep the kodi stuff appart from general utilities.

**Comment by phil65** [comment]
Fine for me in general.
Modulenames should be all lowercase to comply with pep8. (-> kodiutilities.py )
My preference would be "helpers" or "utils" for naming to keep it short and readable.

**Comment by phate89** [comment]
The problem is that yes we will have uniformity here but our whole Python API uses caps initials and no underscore... That's probably confusing..

**Comment by razzeee** [comment]
Done in https://github.com/xbmc/generator-kodi-addon/commit/3cc20e5cff89f1da5eb1199971042fb00d48d68a
and 
https://github.com/xbmc/generator-kodi-addon/commit/e5ce6b26dfd843a87663f3136fe9cf77a640c98c

Will do some quick tests and a new release
